export const INFINITIVE = 'infinitive';
export const GERUND = 'gerund';
export const BARE_INFINITIVE = 'bare infinitive';
export const NO_MATTER = 'no matter';

export const WORDS = new Map([
  ['begin', NO_MATTER],
  ['continue', NO_MATTER],
  ['prefer', NO_MATTER],
  ['start', NO_MATTER],
  ['love', NO_MATTER],
  ['like', NO_MATTER],
  ['hate', NO_MATTER],
  ['used to', BARE_INFINITIVE],
  ['had better', BARE_INFINITIVE],
  ['would rather', BARE_INFINITIVE],
  ['make', BARE_INFINITIVE],
  ['let', BARE_INFINITIVE],
  ['agree', INFINITIVE],
  ['appear', INFINITIVE],
  ['can\'t afford', INFINITIVE],
  ['can\'t wait', INFINITIVE],
  ['encourage', INFINITIVE],
  ['expect', INFINITIVE],
  ['happen', INFINITIVE],
  ['learn', INFINITIVE],
  ['manage', INFINITIVE],
  ['offer', INFINITIVE],
  ['permit', INFINITIVE],
  ['pretend', INFINITIVE],
  ['refuse', INFINITIVE],
  ['seem', INFINITIVE],
  ['tend', INFINITIVE],
  ['threaten', INFINITIVE],
  ['would love ', INFINITIVE],
  ['admit', GERUND],
  ['avoid', GERUND],
  ['can\'t help', GERUND],
  ['can\'t stand', GERUND],
  ['carry on', GERUND],
  ['consider', GERUND],
  ['deny', GERUND],
  ['fancy', GERUND],
  ['give up', GERUND],
  ['keep on', GERUND],
  ['imagine', GERUND],
  ['involve', GERUND],
  ['it\'s no use', GERUND],
  ['it\'s worth', GERUND],
  ['mind', GERUND],
  ['miss', GERUND],
  ['object to', GERUND],
  ['postpone', GERUND],
  ['practise', GERUND],
  ['recommend', GERUND],
  ['risk', GERUND],
  ['suggest', GERUND],
  ['be / get used to', GERUND],
].sort(() => 0.5 - Math.random()));

export const NEXT_QUESTION_TIMEOUT = 500;